export { AGI_ABI, AGI_CONTRACT_ADDRESS } from './agi'
export { GCOIN_ABI, GCOIN_CONTRACT_ADDRESS } from './coin'
export { HP_ABI, HP_CONTRACT_ADDRESS } from './hp'
export { INT_ABI, INT_CONTRACT_ADDRESS } from './int'
export { ABI, CONTRACT_ADDRESS } from './main'
export { PHY_ABI, PHY_CONTRACT_ADDRESS } from './phy'
